### ISSUE TITLE
passing metabase parameters issue

### ISSUE THREAD

**Issue by MohamedLamrabet** [laravolt/metabase#2]
Dear Sir,

I would like to express my gratitude for making it easier to integrate Metabase into Laravel.

I have been attempting to pass Metabase parameters, but I encountered an error in the Metabase chart that says, "There was a problem displaying this chart." However, I noticed that the chart works when I remove ":params="$params" from the <x-metabase> tag.

Here is my Laravel code:
`@php($params = ['user_id' => $user->id])
{{ Log::info($params) }}
<x-metabase :params="$params" dashboard="1" width="100%" height="2000px"></x-metabase>`

This is my Metabase query:
`SELECT user_id, name
FROM users
WHERE user_id = {{ user_id}}`

The Laravel log shows that the array is as follows:
`local.INFO: array (
'user_id' => 1,
)`

Metabase log shows:
"Unknown parameter :user_id."

Thank you in advance for your assistance.

**Comment by uyab** [comment]
You can check the browser network tools and inspect what is the response from metabase endpoint. Usually it is related to metabase variable settings.

**Comment by uyab** [comment]
Oh, it is already there: **"Unknown parameter :user_id."**


Please make sure the settings was correct:
![image](https://user-images.githubusercontent.com/149716/232394328-3f56d279-c977-4d9b-af64-3587f5bb4645.png)

**Comment by MohamedLamrabet** [comment]
I apologize for the delay in responding. I have just seen your response. 

It works perfectly! so you should make the parameter editable in the sharing settings to pass it to the SQL query. 

Thank you very much.
